# Generated by Django 5.2.4 on 2025-08-06 02:44

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('external_id', models.CharField(max_length=50, unique=True)),
                ('categoria', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('area', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('instrucoes', models.TextField(blank=True, null=True)),
                ('imagem_url', models.URLField(max_length=500)),
                ('link_youtube', models.URLField(blank=True, max_length=500, null=True)),
                ('ingredientes', models.JSONField(blank=True, default=list, encoder=django.core.serializers.json.DjangoJSONEncoder, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('data_comentario', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='app_receitas.receita')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='app_receitas.receita')),
            ],
            options={
                'unique_together': {('user', 'receita')},
            },
        ),
        migrations.CreateModel(
            name='ReceitaFavorita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_adicao', models.DateTimeField(auto_now_add=True)),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_receitas.receita')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receitas_favoritas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'receita')},
            },
        ),
    ]
