# Generated by Django 5.2.4 on 2025-08-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_receitas', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='foto',
            field=models.ImageField(blank=True, default='profile_pics/default-avatar.png', upload_to='profile_pics'),
        ),
    ]
