# Generated by Django 5.2.4 on 2025-08-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_receitas', '0004_receita_autor_receita_media_avaliacoes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='receitas_pics'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='imagem_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
